services:
# Client
  twitch.client:
    class: Shoko\TwitchApiBundle\Lib\Client
# Util
  json.transformer:
    class: Shoko\TwitchApiBundle\Util\JsonTransformer
  json.serializer:
    class: Shoko\TwitchApiBundle\Util\JsonSerializer
# Factories
  channel.factory:
    class: Shoko\TwitchApiBundle\Factory\ChannelFactory
  follow.factory:
    class: Shoko\TwitchApiBundle\Factory\FollowFactory
  game.factory:
    class: Shoko\TwitchApiBundle\Factory\GameFactory
  me.factory:
    class: Shoko\TwitchApiBundle\Factory\MeFactory
  my_channel.factory:
    class: Shoko\TwitchApiBundle\Factory\MyChannelFactory
  position.factory:
    class: Shoko\TwitchApiBundle\Factory\PositionFactory
  root.factory:
    class: Shoko\TwitchApiBundle\Factory\RootFactory
  stream.factory:
    class: Shoko\TwitchApiBundle\Factory\StreamFactory
  team.factory:
    class: Shoko\TwitchApiBundle\Factory\TeamFactory
  token.factory:
    class: Shoko\TwitchApiBundle\Factory\TokenFactory
  top.factory:
    class: Shoko\TwitchApiBundle\Factory\TopFactory
  user.factory:
    class: Shoko\TwitchApiBundle\Factory\UserFactory
# Repositories
  channel.repository:
    class: Shoko\TwitchApiBundle\Repository\ChannelRepository
    arguments: ["@twitch.client", "@channel.factory", "@json.transformer"]
  game.repository:
    class: Shoko\TwitchApiBundle\Repository\GameRepository
    arguments: ["@twitch.client", "@top.factory", "@json.transformer"]
  root.repository:
    class: Shoko\TwitchApiBundle\Repository\RootRepository
    arguments: ["@twitch.client", "@root.factory", "@json.transformer"]
  stream.repository:
    class: Shoko\TwitchApiBundle\Repository\StreamRepository
    arguments: ["@twitch.client", "@stream.factory", "@json.transformer"]
  team.repository:
    class: Shoko\TwitchApiBundle\Repository\TeamRepository
    arguments: ["@twitch.client", "@team.factory", "@json.transformer"]
  user.repository:
    class: Shoko\TwitchApiBundle\Repository\UserRepository
    arguments: ["@twitch.client", "@user.factory", "@json.transformer"]
